spring:
  datasource:
    url: jdbc:postgresql://db:5432/urlshortener
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.http.converter.json: TRACE
    com.fasterxml.jackson.databind: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springdoc: DEBUG
